language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - ./gradlew build

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_BRANCH} == 'master' ]] && [[ ${TRAVIS_TAG} == '' ]] && ./gradlew  publish"
